# Automates steps from
# https://cloud.google.com/compute/docs/tutorials/sending-mail/using-mailgun

- name: Setup postfix debconf
  debconf:
    name: postfix
    question: postfix postfix/main_mailer_type
    value: Local Only
    vtype: string

- name: Install postfix
  apt:
    name:
    - postfix
    - libsasl2-modules
    state: present
    update_cache: yes

- name: Remove transports
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '{{ item }}'
    state: absent
  loop:
    - '^default_transport = error'
    - '^relay_transport = error'

- name: Update relayhost
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^relayhost ='
    line: 'relayhost = [smtp.mailgun.org]:2525'

- name: Add smtp block
  blockinfile:
    path: /etc/postfix/main.cf
    block: |
      smtp_tls_security_level = encrypt
      smtp_sasl_auth_enable = yes
      smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
      smtp_sasl_security_options = noanonymous

- name: Create sasl_passwd
  copy:
    content: '[smtp.mailgun.org]:2525 {{ smtp_login }}:{{ smtp_password }}'
    dest: /etc/postfix/sasl_passwd

- name: Run postmap on sasl_passwd
  command: postmap /etc/postfix/sasl_passwd

- name: Delete sasl_passwd
  file:
    path: /etc/postfix/sasl_passwd
    state: absent

- name: Set sasl_passwd.db permissions
  file:
    path: /etc/postfix/sasl_passwd.db
    mode: 0600

- name: Reload configuration
  command: /etc/init.d/postfix restart

